import {useState} from 'react';
import {ArrowRight, Bell, BookOpen, CalendarDays, Check, ChevronDown, CircleDollarSign, Clock, CreditCard, FileText, GraduationCap, LayoutDashboard, LogOut, Menu, MessageSquareText, PlayCircle, Search, Settings, Star, Upload, UserRound, Users, X} from 'lucide-react';

type View='landing'|'login'|'student'|'admin';
const services=[
  {icon:'📖',title:'Clases particulares',text:'Clases personalizadas adaptadas a tu ritmo, nivel y objetivos.',for:'Secundaria y preuniversitario',mode:'Presencial u online',benefit:'Avanzás a tu propio ritmo'},
  {icon:'🎯',title:'Cursos intensivos',text:'Programas estructurados con material incluido para cubrir una materia completa.',for:'Exámenes próximos',mode:'Online con encuentros en vivo',benefit:'Material completo incluido'},
  {icon:'🏆',title:'Ingreso universitario',text:'Preparación específica para exámenes de ingreso a universidades nacionales.',for:'Ingresantes y egresados',mode:'Presencial o grupal online',benefit:'Simulacros y material oficial'}
];
const faqs=['¿Las clases son presenciales u online?','¿Qué materias y niveles trabajamos?','¿Cómo reservo una clase?','¿Qué pasa si necesito cancelar?','¿Cómo recibo el material?','¿Puedo pagar por Mercado Pago?'];

export default function App(){
 const [view,setView]=useState<View>('landing');
 const [mobile,setMobile]=useState(false);
 if(view==='student') return <Portal role="student" onExit={()=>setView('landing')}/>;
 if(view==='admin') return <Portal role="admin" onExit={()=>setView('landing')}/>;
 if(view==='login') return <Login onBack={()=>setView('landing')} onStudent={()=>setView('student')} onAdmin={()=>setView('admin')}/>;
 return <div className="site">
  <div className="install"><b className="mini-logo">AG</b><span><b>Instalá la app en tu celular</b><small>Sin descarga, sin Play Store. Funciona desde el navegador.</small></span><button>📲 Instalar</button></div>
  <header className="header"><button className="brand" onClick={()=>setView('landing')}><b>AG</b><span>Ana García<small>Docente particular</small></span></button><nav className={mobile?'open':''}><a href="#inicio">Inicio</a><a href="#servicios">Clases</a><a href="#servicios">Cursos</a><a href="#proceso">Ingreso</a><a href="#faq">FAQ</a></nav><div className="head-actions"><button className="link-btn" onClick={()=>setView('login')}>Ingresar</button><button className="primary" onClick={()=>setView('login')}>Reservar clase</button><button className="menu" aria-label="Abrir menú" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></div></header>
  <main>
   <section className="hero" id="inicio"><div className="hero-copy"><span className="availability"><i/> Turnos disponibles esta semana</span><h1>Aprendé con confianza.<em>Avanzá con resultados.</em></h1><p>Clases particulares de Matemática, Física y Química para secundaria y preparación para exámenes de ingreso universitario.</p><div className="hero-actions"><button className="primary big" onClick={()=>setView('login')}>Reservar una clase <ArrowRight/></button><a className="ghost" href="https://wa.me/5491112345678">Consultar por WhatsApp</a></div><div className="trust"><span>✨ Clases personalizadas</span><span>🖥️ Presencial y online</span><span>📚 Material incluido</span><span>📈 Seguimiento continuo</span></div></div><div className="hero-visual"><div className="image-wrap"><img src="/classroom.jpg" alt="Estudiante trabajando con docente"/></div><div className="float stat-one"><b>+150</b><span>alumnos acompañados</span></div><div className="float stat-two"><b>93%</b><span>de aprobación en ingreso</span></div></div></section>
   <section className="demo"><b>🎯 Demo del prototipo:</b><button onClick={()=>setView('student')}>Ver portal del alumno</button><button onClick={()=>setView('admin')}>Ver panel administrativo</button><button onClick={()=>setView('login')}>Ver pantalla de acceso</button></section>
   <SectionIntro eyebrow="Servicios" title="¿En qué te puedo ayudar?" text="Cada alumno es distinto. Por eso ofrezco distintas formas de acompañar tu aprendizaje."/>
   <section className="cards" id="servicios">{services.map(s=><article className="service" key={s.title}><span className="service-icon">{s.icon}</span><h3>{s.title}</h3><p>{s.text}</p><dl><div><dt>👤 Para:</dt><dd>{s.for}</dd></div><div><dt>📍 Modalidad:</dt><dd>{s.mode}</dd></div><div><dt>⭐ Beneficio:</dt><dd>{s.benefit}</dd></div></dl><button onClick={()=>setView('login')}>Ver más <ArrowRight/></button></article>)}</section>
   <section className="process" id="proceso"><SectionIntro eyebrow="Proceso" title="Así de simple" text="Reservar una clase lleva menos de 5 minutos."/ ><div className="steps">{[['01','Elegí tu servicio','Clases particulares, curso intensivo o preparación para el ingreso.'],['02','Seleccioná un horario','Revisá la disponibilidad y elegí el horario que mejor te quede.'],['03','Realizá el pago','Abonás por Mercado Pago de forma segura.'],['04','Accedé al material','Recibís la confirmación y todos los materiales de la clase.']].map(x=><article key={x[0]}><b>{x[0]}</b><h4>{x[1]}</h4><p>{x[2]}</p></article>)}</div></section>
   <section className="results"><SectionIntro eyebrow="Resultados" title="Lo que dicen los alumnos" text="Resultados reales, de alumnos de carne y hueso."/><div className="testimonials">{[['Valentina Romero','Ingreso UNC – Medicina','Gracias a las clases pude aprobar el ingreso en el primer intento. Los simulacros fueron clave.'],['Mateo Gutiérrez','Secundaria – 5to año','Después de tres meses de clases particulares, aprobé el trimestre con 8.'],['Sofía Peralta','Ingreso UNVM – Contador','El curso intensivo fue perfecto para organizarme. El material era exactamente lo que pedía el examen.']].map(t=><article key={t[0]}><div className="stars">★★★★★</div><p>“{t[2]}”</p><b>{t[0]}</b><small>{t[1]}</small></article>)}</div></section>
   <section className="faq" id="faq"><SectionIntro eyebrow="FAQ" title="Preguntas frecuentes" text="Todo lo que necesitás saber antes de empezar."/><div>{faqs.map((f,i)=><details key={f} open={i===0}><summary>{f}<ChevronDown/></summary><p>Las clases se adaptan a tus necesidades. Escribime y coordinamos la opción que mejor funcione para vos.</p></details>)}</div></section>
   <section className="cta"><span>¿Listo para empezar?</span><h2>El primer paso siempre es el más importante.</h2><p>Reservá una clase de prueba o consultame sin compromiso.</p><button onClick={()=>setView('login')}>Reservar una clase <ArrowRight/></button></section>
  </main><Footer onLogin={()=>setView('login')}/>
 </div>
}

function SectionIntro({eyebrow,title,text}:{eyebrow:string,title:string,text:string}){return <div className="section-intro"><span>{eyebrow}</span><h2>{title}</h2><p>{text}</p></div>}

function Login({onBack,onStudent,onAdmin}:{onBack:()=>void,onStudent:()=>void,onAdmin:()=>void}){const [email,setEmail]=useState('');return <div className="auth"><div className="auth-art"><button className="brand light" onClick={onBack}><b>AG</b><span>Ana García<small>Docente particular</small></span></button><div><span className="availability"><i/> Tu espacio de aprendizaje</span><h1>Todo lo que necesitás para avanzar.</h1><p>Clases, materiales, reservas y seguimiento en un solo lugar.</p></div><blockquote>“La educación es el arma más poderosa para cambiar el mundo.”</blockquote></div><form className="login-card" onSubmit={e=>{e.preventDefault();onStudent()}}><button type="button" className="back" onClick={onBack}>← Volver al inicio</button><span className="mobile-logo">AG</span><h2>Bienvenido de nuevo</h2><p>Ingresá a tu cuenta para continuar.</p><label>Correo electrónico<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="tu@email.com" required/></label><label>Contraseña<input type="password" placeholder="••••••••" required/></label><div className="form-row"><label className="check"><input type="checkbox"/> Recordarme</label><button type="button" className="text-link">¿Olvidaste tu contraseña?</button></div><button className="primary login-submit">Ingresar</button><div className="divider">o ingresá al demo como</div><div className="demo-login"><button type="button" onClick={onStudent}><GraduationCap/> Alumno</button><button type="button" onClick={onAdmin}><Users/> Administrador</button></div><small className="privacy">Tus datos están protegidos y nunca serán compartidos.</small></form></div>}

const studentNav: ReadonlyArray<readonly [string, any]>=[['Inicio',LayoutDashboard],['Mis clases',CalendarDays],['Materiales',BookOpen],['Cursos',PlayCircle],['Pagos',CreditCard],['Avisos',Bell]];
const adminNav: ReadonlyArray<readonly [string, any]>=[['Dashboard',LayoutDashboard],['Alumnos',Users],['Materiales',FileText],['Calendario',CalendarDays],['Reservas',Clock],['Pagos',CircleDollarSign],['Avisos',MessageSquareText]];
function Portal({role,onExit}:{role:'student'|'admin',onExit:()=>void}){const items=role==='student'?studentNav:adminNav; const [active,setActive]=useState(items[0][0]); return <div className={`portal ${role}`}><aside><div className="portal-brand"><b>AG</b><span>Ana García<small>{role==='student'?'Portal del alumno':'Panel administrativo'}</small></span></div><nav>{items.map(([label,Icon])=><button className={active===label?'active':''} onClick={()=>setActive(label)} key={label}><Icon/>{label}{label==='Avisos'&&<i>3</i>}</button>)}</nav><div className="aside-user"><div>MR</div><span><b>{role==='student'?'Martina Rossi':'Ana García'}</b><small>{role==='student'?'martina@email.com':'Administradora'}</small></span><button onClick={onExit}><LogOut/></button></div></aside><div className="portal-body"><header><div><small>{role==='student'?'Portal del alumno':'Administración'} / {active}</small><h1>{active==='Inicio'||active==='Dashboard'?`¡Hola, ${role==='student'?'Martina':'Ana'}! 👋`:active}</h1></div><div className="portal-tools"><button><Search/></button><button><Bell/><i>3</i></button><div>{role==='student'?'MR':'AG'}</div></div></header><main>{active===items[0][0]?<Dashboard role={role}/>:<ModulePage title={active} role={role}/>}</main><nav className="bottom-nav">{items.slice(0,5).map(([label,Icon])=><button className={active===label?'active':''} onClick={()=>setActive(label)} key={label}><Icon/><small>{label}</small></button>)}</nav></div></div>}

function Dashboard({role}:{role:'student'|'admin'}){if(role==='admin') return <><div className="metrics admin-metrics">{[['Alumnos activos','148','+12%'],['Clases este mes','84','+8%'],['Ingresos',' $1.2M','+14%'],['Reservas pendientes','7','Revisar']].map(m=><article key={m[0]}><span>{m[0]}</span><b>{m[1]}</b><small>{m[2]}</small></article>)}</div><div className="dashboard-grid"><section className="panel"><div className="panel-title"><h2>Clases de hoy</h2><button>Ver calendario</button></div><Schedule/></section><section className="panel"><div className="panel-title"><h2>Acciones rápidas</h2></div><div className="quick admin-quick"><button><UserRound/>Nuevo alumno</button><button><Upload/>Subir material</button><button><CalendarDays/>Nueva clase</button><button><MessageSquareText/>Crear aviso</button></div></section></div><section className="panel table-panel"><div className="panel-title"><h2>Reservas pendientes</h2><button>Ver todas</button></div><table><thead><tr><th>Alumno</th><th>Servicio</th><th>Fecha</th><th>Estado</th></tr></thead><tbody>{[['Lucía Benítez','Matemática','Hoy · 16:00'],['Tomás Paz','Física','Mañana · 10:00'],['Abril Soto','Ingreso UNC','Vie · 18:30']].map(r=><tr key={r[0]}><td><b>{r[0]}</b></td><td>{r[1]}</td><td>{r[2]}</td><td><span className="pending">Pendiente</span></td></tr>)}</tbody></table></section></>;
return <><section className="welcome"><div><span>Tu próxima clase</span><h2>Matemática · Funciones</h2><p><CalendarDays/> Miércoles 8 de agosto · 17:30</p><p><Clock/> Duración: 60 minutos · Modalidad online</p><button>Ingresar a la clase <ArrowRight/></button></div><div className="date-card"><small>AGOSTO</small><b>08</b><span>Miércoles</span></div></section><div className="metrics">{[['Clases completadas','24'],['Horas de estudio','36h'],['Materiales nuevos','8'],['Progreso del curso','72%']].map((m,i)=><article key={m[0]}><span>{m[0]}</span><b>{m[1]}</b>{i===3&&<div className="progress"><i/></div>}</article>)}</div><div className="dashboard-grid"><section className="panel"><div className="panel-title"><h2>Próximas clases</h2><button>Ver calendario</button></div><Schedule/></section><section className="panel"><div className="panel-title"><h2>Accesos rápidos</h2></div><div className="quick"><button><CalendarDays/>Reservar clase</button><button><BookOpen/>Ver materiales</button><button><PlayCircle/>Continuar curso</button><button><MessageSquareText/>Enviar consulta</button></div></section></div></>}
function Schedule(){return <div className="schedule">{[['09 AGO','Física','Leyes de Newton','18:00'],['12 AGO','Química','Enlaces químicos','16:30'],['15 AGO','Matemática','Repaso para examen','17:30']].map(x=><div key={x[0]}><time>{x[0]}</time><span><b>{x[1]}</b><small>{x[2]}</small></span><strong>{x[3]}</strong></div>)}</div>}
function ModulePage({title,role}:{title:string,role:string}){return <><div className="module-head"><div><p>Gestioná y consultá toda la información desde acá.</p></div><button className="primary">+ {role==='admin'?'Crear nuevo':'Nueva reserva'}</button></div><section className="panel module"><div className="module-toolbar"><label><Search/><input placeholder={`Buscar en ${title.toLowerCase()}...`}/></label><button>Todos</button><button>Más recientes</button></div><div className="empty-icon">{title==='Materiales'?<BookOpen/>:<FileText/>}</div><h2>{title}</h2><p>Este módulo está listo para conectarse con tus datos reales.</p><div className="module-cards">{[1,2,3].map(n=><article key={n}><span>{title.slice(0,1)}{n}</span><div><b>{title} · Elemento {n}</b><small>Actualizado recientemente</small></div><button>Ver detalle</button></article>)}</div></section></>}
function Footer({onLogin}:{onLogin:()=>void}){return <footer><div><div className="footer-brand"><b>AG</b><span><strong>Ana García</strong><p>Docente particular de Matemática, Física y Química. Villa del Parque, CABA.</p></span></div><div><h4>Servicios</h4><a>Clases particulares</a><a>Cursos intensivos</a><a>Ingreso universitario</a></div><div><h4>Plataforma</h4><button onClick={onLogin}>Acceso de alumnos</button><a>Preguntas frecuentes</a><a>Privacidad</a></div><div><h4>Contacto</h4><a>+54 9 11 1234-5678</a><a>ana@anagarcia.com.ar</a><a>Villa del Parque, CABA</a></div></div><small>© 2026 Ana García – Docente particular. Todos los derechos reservados.</small></footer>}
