import {useState} from 'react';
import {ArrowRight,Bell,BookOpen,CalendarDays,Check,ChevronDown,CircleDollarSign,Clock,Copy,CreditCard,FileText,GraduationCap,LayoutDashboard,LogOut,Menu,MessageSquareText,PlayCircle,Search,Star,Upload,UserRound,Users,X} from 'lucide-react';

type View='landing'|'login'|'student'|'admin';
const WA='https://wa.me/5491161039031';
const ASSET=import.meta.env.BASE_URL;
const services=[
 {tone:'blue',icon:'CI',title:'Clases individuales',text:'Clases personalizadas adaptadas a cada estudiante.',for:'Secundarios y universitarios',mode:'Presencial u online',benefit:'Avanzás a tu propio ritmo',price:'$40.000',period:'por encuentro de 60 min'},
 {tone:'orange',icon:'CBC',title:'Acompañamiento CBC',text:'Encuentros grupales online para resolver ejercicios y completar contenidos.',for:'Matemática 51, Química y Biofísica',mode:'Online · hasta 5 participantes',benefit:'Consultás tus dudas específicas',price:'$120.000',period:'por 4 encuentros mensuales'},
 {tone:'green',icon:'UTN',title:'Ingreso UTN',text:'Encuentros grupales con desarrollo del programa y ejercicios de exámenes.',for:'Ingresantes de todas las regionales',mode:'Online · hasta 5 participantes',benefit:'Material complementario personalizado',price:'$120.000',period:'por 4 encuentros mensuales'}
];
const subjects=[
 {name:'Matemáticas',img:'https://ciencias-exactas.com.ar/wp-content/uploads/2019/01/matematica-icono.jpg'},
 {name:'Álgebra',img:'https://ciencias-exactas.com.ar/wp-content/uploads/2019/01/algebra-icono.jpg'},
 {name:'Análisis Matemático I y II',img:'https://ciencias-exactas.com.ar/wp-content/uploads/2019/01/analisis-matematico-icono.jpg'},
 {name:'Química General',img:'https://ciencias-exactas.com.ar/wp-content/uploads/2019/01/quimica-icono.jpg'},
 {name:'Física',img:'https://ciencias-exactas.com.ar/wp-content/uploads/2019/01/fisica-icono.jpg'},
 {name:'Probabilidad y Estadística',img:'https://ciencias-exactas.com.ar/wp-content/uploads/2019/01/probabilidad-estadistica-icono.jpg'}
];
const faqs=['¿Las clases son presenciales u online?','¿Qué materias y niveles trabajamos?','¿Cómo reservo una clase?','¿Qué pasa si necesito cancelar?','¿Cómo recibo el material?','¿Cómo se valida el pago?'];

export default function App(){
 const [view,setView]=useState<View>('landing'); const [mobile,setMobile]=useState(false);
 if(view==='student') return <Portal role="student" onExit={()=>setView('landing')}/>;
 if(view==='admin') return <Portal role="admin" onExit={()=>setView('landing')}/>;
 if(view==='login') return <Login onBack={()=>setView('landing')} onStudent={()=>setView('student')} onAdmin={()=>setView('admin')}/>;
 return <div className="site">
  <div className="contact-strip"><a href={WA}>WhatsApp: 11 6103-9031</a><a href="mailto:profeexactasmg@gmail.com">profeexactasmg@gmail.com</a><span>Recoleta, CABA</span></div>
  <header className="header"><Brand/><nav className={mobile?'open':''}><a href="#inicio">Inicio</a><a href="#servicios">Servicios</a><a href="#materias">Materias</a><a href="#modalidades">Modalidades</a><a href="#faq">FAQ</a></nav><div className="head-actions"><button className="link-btn" onClick={()=>setView('login')}>Ingresar</button><button className="primary" onClick={()=>setView('login')}>Reservar clase</button><button className="menu" aria-label="Abrir menú" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></div></header>
  <main>
   <section className="hero" id="inicio"><div className="hero-copy"><span className="availability"><i/> Turnos disponibles</span><h1>Apoyo académico para <em>seguir creciendo.</em></h1><p>Clases particulares para estudiantes secundarios y universitarios: Matemática, Física, Química, Estadística, Análisis Matemático, Álgebra y más.</p><div className="hero-actions"><button className="primary big" onClick={()=>setView('login')}>Reservar una clase <ArrowRight/></button><a className="ghost" href={WA}>Consultar por WhatsApp</a></div><div className="trust"><span><Check/> Atención personalizada</span><span><Check/> Presencial y online</span><span><Check/> Material incluido</span><span><Check/> Seguimiento continuo</span></div></div><div className="hero-visual"><div className="image-wrap"><img src={`${ASSET}classroom.jpg`} alt="Aula de Ciencias Exactas"/></div><div className="float stat-one"><b>+20</b><span>años acompañando alumnos</span></div><div className="float stat-two"><b>5</b><span>alumnos máximo por grupo</span></div></div></section>
   <section className="demo"><b>Explorá la plataforma:</b><button onClick={()=>setView('student')}>Portal del alumno</button><button onClick={()=>setView('admin')}>Panel administrativo</button><button onClick={()=>setView('login')}>Pantalla de acceso</button></section>
   <SectionIntro eyebrow="Servicios" title="Elegí cómo avanzar" text="Propuestas concretas para tus objetivos y tu ritmo de estudio."/>
   <section className="cards" id="servicios">{services.map(s=><article className={`service ${s.tone}`} key={s.title}><span className="service-icon">{s.icon}</span><h3>{s.title}</h3><p>{s.text}</p><dl><div><dt>Para</dt><dd>{s.for}</dd></div><div><dt>Modalidad</dt><dd>{s.mode}</dd></div><div><dt>Beneficio</dt><dd>{s.benefit}</dd></div></dl><div className="service-price"><b>{s.price}</b><small>{s.period}</small></div><button onClick={()=>setView('login')}>Elegir servicio <ArrowRight/></button></article>)}</section>
   <section className="subjects-section" id="materias"><SectionIntro eyebrow="Materias" title="Ciencias exactas, de principio a fin" text="Reutilizamos la propuesta académica de Ciencias Exactas."/><div className="subjects">{subjects.map(s=><article key={s.name}><img src={s.img} alt=""/><h3>{s.name}</h3></article>)}</div></section>
   <section className="process"><SectionIntro eyebrow="Proceso" title="Así de simple" text="Reservar o sumarte a un grupo lleva pocos minutos."/><div className="steps">{[['01','Elegí tu servicio','Seleccioná una clase individual, acompañamiento CBC o ingreso UTN.'],['02','Seleccioná un horario','Elegí un turno disponible. Los grupos se habilitan a demanda.'],['03','Realizá el pago','Pagá con QR de MODO o transferencia y enviá el comprobante.'],['04','Esperá la confirmación','La administración valida el pago y carga el enlace de Google Meet.']].map(x=><article key={x[0]}><b>{x[0]}</b><h4>{x[1]}</h4><p>{x[2]}</p></article>)}</div></section>
   <section className="modalities" id="modalidades"><SectionIntro eyebrow="Modalidades" title="Como te quede mejor" text="Una experiencia clara, cercana y en vivo."/><div><article><span>P</span><h3>Presencial</h3><p>Clases individuales en J. E. Uriburu 1438 PB, Recoleta, CABA.</p></article><article><span>ON</span><h3>Online</h3><p>Clase en vivo con pizarrón de aula y excelente calidad de imagen y sonido.</p></article><article><span>1:1</span><h3>Individual</h3><p>Atención personalizada de 60 minutos, adaptada a cada estudiante.</p></article><article><span>5</span><h3>Grupal</h3><p>Cuatro encuentros mensuales de 2 horas. Hasta 5 participantes y cupo limitado.</p></article></div></section>
   <section className="results"><SectionIntro eyebrow="Experiencias" title="Lo que dicen los alumnos" text="Testimonios enviados desde el portal y aprobados antes de publicarse."/><div className="testimonials">{[['Valentina Romero','Excelente acompañamiento y explicaciones muy claras.'],['Mateo Gutiérrez','Pude ordenar los temas y llegar con confianza al examen.'],['Sofía Peralta','El grupo reducido hizo que pudiera consultar todas mis dudas.']].map(t=><article key={t[0]}><div className="stars">5/5</div><p>“{t[1]}”</p><div className="testimonial-person"><span>{t[0][0]}</span><b>{t[0]}</b></div></article>)}</div></section>
   <section className="faq" id="faq"><SectionIntro eyebrow="FAQ" title="Preguntas frecuentes" text="Contenido preliminar hasta definir las respuestas finales."/><div>{faqs.map((f,i)=><details key={f} open={i===0}><summary>{f}<ChevronDown/></summary><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Esta respuesta será reemplazada con la información definitiva.</p></details>)}</div></section>
   <section className="cta"><img src={`${ASSET}logo-ciencias-exactas.jpg`} alt="Ciencias Exactas"/><h2>¿Empezamos a preparar esa materia?</h2><p>Reservá un turno o escribinos por WhatsApp.</p><button onClick={()=>setView('login')}>Reservar una clase <ArrowRight/></button></section>
  </main><Footer onLogin={()=>setView('login')}/>
 </div>
}

function Brand(){return <button className="brand"><img src={`${ASSET}logo-ciencias-exactas.jpg`} alt="Ciencias Exactas"/></button>}
function SectionIntro({eyebrow,title,text}:{eyebrow:string,title:string,text:string}){return <div className="section-intro"><span>{eyebrow}</span><h2>{title}</h2><p>{text}</p></div>}
function Login({onBack,onStudent,onAdmin}:{onBack:()=>void,onStudent:()=>void,onAdmin:()=>void}){const [email,setEmail]=useState('');return <div className="auth"><div className="auth-art"><Brand/><div><span className="availability"><i/> Tu espacio de aprendizaje</span><h1>Todo lo que necesitás para avanzar.</h1><p>Clases, materiales, reservas, pagos y seguimiento en un solo lugar.</p></div><blockquote>Aprendizaje, acompañamiento y resultados.</blockquote></div><form className="login-card" onSubmit={e=>{e.preventDefault();onStudent()}}><button type="button" className="back" onClick={onBack}>&lt;- Volver al inicio</button><img className="login-logo" src={`${ASSET}logo-ciencias-exactas.jpg`} alt="Ciencias Exactas"/><h2>Bienvenido de nuevo</h2><p>Ingresá a tu cuenta para continuar.</p><label>Correo electrónico<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="tu@email.com" required/></label><label>Contraseña<input type="password" placeholder="********" required/></label><div className="form-row"><label className="check"><input type="checkbox"/> Recordarme</label><button type="button" className="text-link">¿Olvidaste tu contraseña?</button></div><button className="primary login-submit">Ingresar</button><div className="divider">demo</div><div className="demo-login"><button type="button" onClick={onStudent}><GraduationCap/> Alumno</button><button type="button" onClick={onAdmin}><Users/> Administración</button></div></form></div>}

const studentNav:ReadonlyArray<readonly[string,any]>=[['Inicio',LayoutDashboard],['Materiales',BookOpen],['Calendario',CalendarDays],['Reservar clase',Clock],['Mis reservas',FileText],['Pagos',CreditCard],['Cursos',PlayCircle],['Avisos',Bell],['Mi testimonio',Star]];
const adminNav:ReadonlyArray<readonly[string,any]>=[['Dashboard',LayoutDashboard],['Alumnos',Users],['Materiales',FileText],['Calendario',CalendarDays],['Reservas',Clock],['Pagos',CircleDollarSign],['Testimonios',Star],['Avisos',MessageSquareText]];
function Portal({role,onExit}:{role:'student'|'admin',onExit:()=>void}){const items=role==='student'?studentNav:adminNav;const[active,setActive]=useState(items[0][0]);return <div className={`portal ${role}`}><aside><div className="portal-brand"><img src={`${ASSET}logo-ciencias-exactas.jpg`} alt="Ciencias Exactas"/><small>{role==='student'?'Portal del alumno':'Panel administrativo'}</small></div><nav>{items.map(([label,Icon])=><button className={active===label?'active':''} onClick={()=>setActive(label)} key={label}><Icon/>{label}{(label==='Avisos'||label==='Pagos')&&<i>2</i>}</button>)}</nav><div className="aside-user"><div>{role==='student'?'VR':'MG'}</div><span><b>{role==='student'?'Valentina Romero':'Miriam Güeper'}</b><small>{role==='student'?'Alumno':'Administración'}</small></span><button onClick={onExit}><LogOut/></button></div></aside><div className="portal-body"><header><div><small>{role==='student'?'Portal del alumno':'Administración'} / {active}</small><h1>{active==='Inicio'||active==='Dashboard'?`¡Hola, ${role==='student'?'Valentina':'Miriam'}!`:active}</h1></div><div className="portal-tools"><button><Search/></button><button><Bell/><i>2</i></button><div>{role==='student'?'VR':'MG'}</div></div></header><main>{active===items[0][0]?<Dashboard role={role}/>:active==='Reservar clase'?<Booking/>:active==='Mi testimonio'?<TestimonialForm/>:<ModulePage title={active} role={role}/>}</main><nav className="bottom-nav">{items.slice(0,5).map(([label,Icon])=><button className={active===label?'active':''} onClick={()=>setActive(label)} key={label}><Icon/><small>{label}</small></button>)}</nav></div></div>}

function Dashboard({role}:{role:'student'|'admin'}){if(role==='admin')return <><div className="metrics admin-metrics">{[['Alumnos activos','148','+12%'],['Clases este mes','84','+8%'],['Pagos por validar','4','Revisar'],['Testimonios pendientes','3','Moderar']].map(m=><article key={m[0]}><span>{m[0]}</span><b>{m[1]}</b><small>{m[2]}</small></article>)}</div><div className="dashboard-grid"><section className="panel"><div className="panel-title"><h2>Clases de hoy</h2><button>Ver calendario</button></div><Schedule/></section><section className="panel"><div className="panel-title"><h2>Acciones rápidas</h2></div><div className="quick"><button><UserRound/>Nuevo alumno</button><button><Upload/>Subir material</button><button><CalendarDays/>Nuevo turno</button><button><MessageSquareText/>Crear aviso</button></div></section></div><section className="panel table-panel"><div className="panel-title"><h2>Pagos pendientes de validación</h2><button>Ver todos</button></div><table><tbody>{[['Lucía Benítez','Transferencia','Hace 8 min'],['Tomás Paz','MODO QR','Hace 21 min'],['Abril Soto','Transferencia','Hace 34 min']].map(r=><tr key={r[0]}><td><b>{r[0]}</b></td><td>{r[1]}</td><td>{r[2]}</td><td><button className="approve">Aprobar</button></td></tr>)}</tbody></table></section></>;
return <><section className="renewal"><Bell/><div><b>Tu abono vence en 7 días</b><span>Conservá tu día y horario renovando el acompañamiento CBC.</span></div><button>Renovar abono</button></section><section className="welcome"><div><span>Tu próxima clase</span><h2>Matemática 51 · Funciones</h2><p><CalendarDays/> Miércoles 8 de agosto · 17:30</p><p><Clock/> Duración: 2 horas · Modalidad online</p><button>Ver enlace de Meet <ArrowRight/></button></div><div className="date-card"><small>AGOSTO</small><b>08</b><span>Miércoles</span></div></section><div className="metrics">{[['Clases del mes','3 de 4'],['Estado del pago','Al día'],['Materiales nuevos','2'],['Cupo del grupo','4 de 5']].map(m=><article key={m[0]}><span>{m[0]}</span><b>{m[1]}</b></article>)}</div><div className="dashboard-grid"><section className="panel"><div className="panel-title"><h2>Próximas clases</h2><button>Ver calendario</button></div><Schedule/></section><section className="panel"><div className="panel-title"><h2>Accesos rápidos</h2></div><div className="quick"><button><CalendarDays/>Reservar clase</button><button><BookOpen/>Ver materiales</button><button><CreditCard/>Mis pagos</button><button><MessageSquareText/>Enviar consulta</button></div></section></div></>}
function Schedule(){return <div className="schedule">{[['09 AGO','Matemática 51','Funciones','18:00'],['16 AGO','Matemática 51','Derivadas','18:00'],['23 AGO','Matemática 51','Integrales','18:00']].map(x=><div key={x[0]}><time>{x[0]}</time><span><b>{x[1]}</b><small>{x[2]}</small></span><strong>{x[3]}</strong></div>)}</div>}

function Booking(){const[step,setStep]=useState(1);const[selected,setSelected]=useState('');return <section className="booking panel"><div className="booking-steps"><span className={step>=1?'active':''}>1 Servicio</span><span className={step>=2?'active':''}>2 Horario</span><span className={step>=3?'active':''}>3 Pago</span></div>{step===1&&<><h2>¿Qué servicio necesitás?</h2><div className="booking-options">{services.map(s=><button className={selected===s.title?'selected':''} onClick={()=>setSelected(s.title)} key={s.title}><span>{s.icon}</span><div><b>{s.title}</b><small>{s.period}</small></div><strong>{s.price}</strong></button>)}</div><button className="primary booking-next" disabled={!selected} onClick={()=>setStep(2)}>Continuar</button></>}{step===2&&<><h2>Elegí un horario disponible</h2><p>El cupo se guarda durante 2 horas mientras enviás el comprobante.</p><div className="slots">{['Lun 18:00','Mar 10:00','Mié 16:00','Jue 18:00','Vie 11:00'].map((x,i)=><button className={i===2?'full':''} disabled={i===2} key={x}>{x}<small>{i===2?'Cupo completo':selected==='Clases individuales'?'60 min':'2 h'}</small></button>)}</div><button className="primary booking-next" onClick={()=>setStep(3)}>Continuar al pago</button></>}{step===3&&<Payment selected={selected}/>}</section>}
function Payment({selected}:{selected:string}){const[method,setMethod]=useState<'modo'|'transfer'>('modo');return <><h2>Realizar el pago</h2><div className="policy"><b>Política de cancelación</b><span>Cancelación hasta 48 horas antes y reprogramación hasta 24 horas antes. Fuera de término se pierde el importe.</span></div><div className="payment-tabs"><button className={method==='modo'?'active':''} onClick={()=>setMethod('modo')}>QR de MODO</button><button className={method==='transfer'?'active':''} onClick={()=>setMethod('transfer')}>Transferencia</button></div>{method==='modo'?<div className="payment-box"><div className="qr">MODO<br/><small>QR</small></div><h3>Escaneá el código con MODO</h3><p>Al finalizar, enviá el comprobante por WhatsApp o correo.</p></div>:<div className="payment-box bank"><p><span>Alias</span><b>profeexactas</b><Copy/></p><p><span>CBU</span><b>0070325130004036330808</b><Copy/></p><p><span>Banco</span><b>Galicia</b></p><p><span>Titular</span><b>Miriam Gueper</b></p></div>}<div className="pending-note"><Clock/>La reserva de {selected} quedará pendiente de validación manual.</div><div className="receipt-actions"><a href={WA}>Enviar por WhatsApp</a><a href="mailto:profeexactasmg@gmail.com">Enviar por correo</a></div></>}
function TestimonialForm(){const[text,setText]=useState('');const[rating,setRating]=useState(5);return <section className="panel testimonial-form"><h2>Mi testimonio</h2><p>Tu comentario se publicará con tu nombre y foto de perfil después de ser aprobado.</p><div className="rating">{[1,2,3,4,5].map(n=><button onClick={()=>setRating(n)} className={n<=rating?'active':''} key={n}>*</button>)}</div><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Contanos tu experiencia..."/><button className="primary">{text?'Guardar cambios':'Enviar para aprobación'}</button><small>Podrás editarlo cuando quieras. La eliminación la gestiona la administración.</small></section>}
function ModulePage({title,role}:{title:string,role:string}){return <><div className="module-head"><button className="primary">+ {role==='admin'?'Crear nuevo':'Nueva consulta'}</button></div><section className="panel module"><div className="module-toolbar"><label><Search/><input placeholder={`Buscar en ${title.toLowerCase()}...`}/></label><button>Todos</button><button>Más recientes</button></div><div className="empty-icon">{title==='Materiales'?<BookOpen/>:<FileText/>}</div><h2>{title}</h2><p>Este módulo está listo para conectarse con los datos reales.</p><div className="module-cards">{[1,2,3].map(n=><article key={n}><span>{title.slice(0,1)}{n}</span><div><b>{title} · Elemento {n}</b><small>{title==='Pagos'?'Pendiente de validación':'Actualizado recientemente'}</small></div><button>{role==='admin'&&title==='Testimonios'?'Aprobar':'Ver detalle'}</button></article>)}</div></section></>}
function Footer({onLogin}:{onLogin:()=>void}){return <footer><div><div className="footer-brand"><img src={`${ASSET}logo-ciencias-exactas.jpg`} alt="Ciencias Exactas"/><span><strong>Miriam Güeper</strong><p>Profesora particular de Ciencias Exactas.</p></span></div><div><h4>Servicios</h4><a>Clases individuales</a><a>Acompañamiento CBC</a><a>Ingreso UTN</a></div><div><h4>Plataforma</h4><button onClick={onLogin}>Acceso de alumnos</button><a>Materias</a><a>Preguntas frecuentes</a></div><div><h4>Contacto</h4><a href={WA}>+54 9 11 6103-9031</a><a href="mailto:profeexactasmg@gmail.com">profeexactasmg@gmail.com</a><a>J. E. Uriburu 1438 PB<br/>Recoleta, CABA</a></div></div><small>© 2026 Ciencias Exactas · Miriam Güeper.</small></footer>}

