import {useState} from 'react';
import {ArrowRight,Bell,BookOpen,CalendarDays,Check,ChevronDown,CircleDollarSign,Clock,Copy,CreditCard,FileText,GraduationCap,LayoutDashboard,LogOut,Menu,MessageSquareText,PlayCircle,Search,Star,Upload,UserRound,Users,X} from 'lucide-react';

type View='landing'|'login'|'forgot'|'service'|'student'|'admin';
const WA='https://wa.me/5491161039031';
const ASSET=import.meta.env.BASE_URL;
const services=[
 {tone:'blue',icon:'CI',title:'Clases individuales',text:'Clases personalizadas adaptadas a cada estudiante.',for:'Secundarios y universitarios',mode:'Presencial u online',benefit:'Avanzás a tu propio ritmo',price:'$40.000',period:'por encuentro de 60 min'},
 {tone:'orange',icon:'CBC',title:'Acompañamiento CBC',text:'Encuentros grupales online para resolver ejercicios y completar contenidos.',for:'Matemática 51, Química y Biofísica',mode:'Online · hasta 5 participantes',benefit:'Consultás tus dudas específicas',price:'$120.000',period:'por 4 encuentros mensuales'},
 {tone:'green',icon:'UTN',title:'Ingreso UTN',text:'Encuentros grupales con desarrollo del programa y ejercicios de exámenes.',for:'Ingresantes de todas las regionales',mode:'Online · hasta 5 participantes',benefit:'Material complementario personalizado',price:'$120.000',period:'por 4 encuentros mensuales'}
];
const subjects=[
 {name:'Matemáticas',img:'https://ciencias-exactas.com.ar/wp-content/uploads/2019/01/matematica-icono.jpg'},
 {name:'Álgebra',img:'https://ciencias-exactas.com.ar/wp-content/uploads/2019/01/algebra-icono.jpg'},
 {name:'Análisis Matemático I y II',img:'https://ciencias-exactas.com.ar/wp-content/uploads/2019/01/analisis-matematico-icono.jpg'},
 {name:'Química General',img:'https://ciencias-exactas.com.ar/wp-content/uploads/2019/01/quimica-icono.jpg'},
 {name:'Física',img:'https://ciencias-exactas.com.ar/wp-content/uploads/2019/01/fisica-icono.jpg'},
 {name:'Probabilidad y Estadística',img:'https://ciencias-exactas.com.ar/wp-content/uploads/2019/01/probabilidad-estadistica-icono.jpg'}
];
const faqs=[
 ['¿Las clases son presenciales u online?','Podés elegir modalidad presencial en Recoleta u online en vivo, con la misma atención personalizada.'],
 ['¿Qué materias y niveles trabajamos?','Matemática, Física, Química, Álgebra, Análisis y Estadística para nivel secundario, CBC, universitario e ingresos.'],
 ['¿Cómo reservo una clase?','Elegís el servicio y horario desde la plataforma. La reserva queda confirmada cuando validamos el pago.'],
 ['¿Qué pasa si necesito cancelar?','Podés cancelar hasta 48 horas antes o reprogramar hasta 24 horas antes del encuentro.'],
 ['¿Cómo recibo el material?','Todo el material complementario queda disponible dentro de tu portal de alumno.'],
 ['¿Cómo se valida el pago?','Podés pagar por transferencia o MODO y adjuntar el comprobante para la validación manual.']
];

export default function App(){
 const [view,setView]=useState<View>('landing'); const [mobile,setMobile]=useState(false); const [service,setService]=useState(services[0]);
 if(view==='student') return <Portal role="student" onExit={()=>setView('landing')}/>;
 if(view==='admin') return <Portal role="admin" onExit={()=>setView('landing')}/>;
 if(view==='login') return <Login onBack={()=>setView('landing')} onForgot={()=>setView('forgot')} onStudent={()=>setView('student')} onAdmin={()=>setView('admin')}/>;
 if(view==='forgot') return <Forgot onBack={()=>setView('login')}/>;
 if(view==='service') return <ServiceDetail service={service} onBack={()=>setView('landing')} onBook={()=>setView('login')}/>;
 return <div className="site">
  <header className="header"><Brand/><nav className={mobile?'open':''}><a href="#inicio">Inicio</a><a href="#servicios">Clases</a><a href="#servicios">Cursos</a><a href="#servicios">Ingreso</a><a href="#faq">FAQ</a><button onClick={()=>setView('login')}>Ingresar</button></nav><button className="menu" aria-label="Abrir menú" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></header>
  <main>
   <section className="hero" id="inicio"><h1><span>Miriam, profesora particular de Ciencias Exactas.</span> Contame qué estás preparando y vemos cómo encararlo.</h1><button className="availability" onClick={()=>setView('login')}><span>Turnos disponibles esta semana</span><b>Reservar una clase <ArrowRight/></b></button><p>Matemática · Física · Química · Secundaria · CBC · Universidad</p><a className="whatsapp" href={WA}>Escribime por WhatsApp <ArrowRight/></a><div className="trust"><span><Check/> Atención personalizada</span><span><Check/> Presencial y online</span><span><Check/> Material incluido</span></div></section>
   <section className="about" id="sobre-mi"><div><SectionIntro eyebrow="Sobre mí" title="Hola, soy Miriam." text="Hace más de 20 años acompaño estudiantes a ordenar ideas, superar bloqueos y recuperar la confianza frente a las ciencias exactas."/><blockquote>“Mi objetivo es que entiendas la materia y llegues a cada examen con seguridad.”</blockquote></div><div className="about-photo"><img src={`${ASSET}profe-miriam.jpg`} alt="Miriam, profesora de Ciencias Exactas"/><span><b>+20 años</b> enseñando a entender</span></div></section>
   <section className="services-wrap" id="servicios"><SectionIntro eyebrow="Clases y cursos" title="Elegí cómo querés avanzar" text="Cada propuesta se adapta a tu objetivo, tus tiempos y el punto exacto en el que estás."/><div className="cards">{services.map((s,i)=><article className="service" key={s.title}><span>0{i+1}</span><h3>{i===1?'Cursos intensivos':i===2?'Ingreso Universitario':s.title}</h3><p>{s.text}</p><ul><li>{s.for}</li><li>{s.mode}</li><li>{s.benefit}</li></ul><button onClick={()=>{setService(s);setView('service')}}>Ver más <ArrowRight/></button></article>)}</div></section>
   <section className="subjects-section" id="materias"><SectionIntro eyebrow="Materias" title="Lo difícil se vuelve abordable" text="Trabajamos cada tema desde la base hasta que puedas resolverlo con seguridad."/><div className="subjects">{subjects.map((s,i)=><article key={s.name}><span>0{i+1}</span><h3>{s.name}</h3></article>)}</div></section>
   <section className="process"><SectionIntro eyebrow="Cómo trabajamos" title="Un camino claro, paso a paso" text="Sin vueltas. Primero entendemos qué necesitás y después armamos el mejor plan."/><div className="steps">{[['01','Me contás qué estás preparando','Materia, fecha, temas y dónde sentís que está el bloqueo.'],['02','Elegimos modalidad y horario','Presencial u online, individual o grupal, según tu objetivo.'],['03','Trabajamos sobre lo importante','Teoría clara, ejercicios concretos y material para seguir practicando.'],['04','Llegás con otra seguridad','Seguimiento, consultas y una estrategia real para tu examen.']].map(x=><article key={x[0]}><b>{x[0]}</b><h4>{x[1]}</h4><p>{x[2]}</p></article>)}</div></section>
   <section className="results"><SectionIntro eyebrow="Experiencias" title="Lo que cambia cuando entendés" text="Alumnos que dejaron de pelearse con la materia y empezaron a avanzar."/><div className="testimonials">{[['Valentina Romero','Excelente acompañamiento y explicaciones muy claras. Llegué al examen entendiendo de verdad.'],['Mateo Gutiérrez','Pude ordenar los temas y recuperar la confianza. La diferencia fue enorme.']].map(t=><article key={t[0]}><p>“{t[1]}”</p><div><span>{t[0][0]}</span><b>{t[0]}</b><small>Alumno/a verificado/a</small></div></article>)}</div></section>
   <section className="modalities" id="modalidades"><SectionIntro eyebrow="Modalidades" title="Como te quede mejor" text="La misma cercanía y claridad, estés donde estés."/><div>{[['P','Presencial','En Recoleta, CABA, con un espacio preparado para trabajar sin distracciones.'],['ON','Online','En vivo, con pizarrón y material compartido. Sin perder calidad ni cercanía.'],['1:1','Individual','Todo el encuentro enfocado en tus dudas y en tu propio ritmo.'],['5','Grupal','Grupos reducidos de hasta cinco personas con objetivos compartidos.']].map(x=><article key={x[1]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
   <section className="faq" id="faq"><SectionIntro eyebrow="Preguntas frecuentes" title="Antes de empezar" text="Todo lo que necesitás saber para reservar y comenzar."/><div>{faqs.map(([q,a],i)=><details key={q} open={i===0}><summary>{q}<ChevronDown/></summary><p>{a}</p></details>)}</div></section>
   <section className="cta"><p>¿Tenés un examen cerca?</p><h2>Empecemos por ordenar el problema.</h2><button onClick={()=>setView('login')}>Reservar una clase <ArrowRight/></button><a href={WA}>O escribime por WhatsApp</a></section>
  </main><Footer onLogin={()=>setView('login')}/>
 </div>
}

function Brand(){return <button className="brand"><b>MG</b><span>Miriam Güeper<small>Profesora particular</small></span></button>}
function SectionIntro({eyebrow,title,text}:{eyebrow:string,title:string,text:string}){return <div className="section-intro"><span>{eyebrow}</span><h2>{title}</h2><p>{text}</p></div>}
function Login({onBack,onForgot,onStudent,onAdmin}:{onBack:()=>void,onForgot:()=>void,onStudent:()=>void,onAdmin:()=>void}){const [email,setEmail]=useState('');return <div className="auth"><form className="login-card" onSubmit={e=>{e.preventDefault();onStudent()}}><button type="button" className="back" onClick={onBack}>← Volver al inicio</button><Brand/><h1>Ingresar</h1><p>Accedé a tus clases, materiales y reservas.</p><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="tu@email.com" required/></label><label>Contraseña<input type="password" placeholder="••••••••" required/></label><button type="button" className="text-link" onClick={onForgot}>¿Olvidaste tu contraseña?</button><button className="primary login-submit">Ingresar <ArrowRight/></button><div className="divider">Explorar demo</div><div className="demo-login"><button type="button" onClick={onStudent}><GraduationCap/> Alumno</button><button type="button" onClick={onAdmin}><Users/> Administración</button></div></form></div>}
function Forgot({onBack}:{onBack:()=>void}){return <div className="auth"><form className="login-card" onSubmit={e=>e.preventDefault()}><button type="button" className="back" onClick={onBack}>← Volver al ingreso</button><Brand/><h1>Recuperar contraseña</h1><p>Ingresá tu email y te enviaremos las instrucciones.</p><label>Email<input type="email" placeholder="tu@email.com" required/></label><button className="primary login-submit">Enviar instrucciones <ArrowRight/></button></form></div>}
function ServiceDetail({service,onBack,onBook}:{service:typeof services[number],onBack:()=>void,onBook:()=>void}){return <div className="detail"><header><Brand/><button onClick={onBack}>Volver al inicio</button></header><main><button className="back" onClick={onBack}>← Volver a servicios</button><div className="detail-title"><span>Clases y cursos</span><h1>{service.title}</h1><p>{service.text}</p></div><div className="detail-grid"><section><h2>Una propuesta enfocada en vos</h2><p>Empezamos por detectar qué necesitás, ordenamos los conceptos y trabajamos con ejercicios concretos para que avances con seguridad.</p><h3>¿Qué incluye?</h3><ul><li>Explicaciones claras y adaptadas a tu nivel.</li><li>Material complementario para practicar.</li><li>Seguimiento entre encuentros.</li><li>Plan de trabajo según tu fecha de examen.</li></ul></section><aside><span>Modalidad</span><b>{service.mode}</b><span>Inversión</span><b>{service.price}</b><small>{service.period}</small><button onClick={onBook}>Reservar una clase <ArrowRight/></button></aside></div><section className="cta"><p>¿No sabés si esta opción es para vos?</p><h2>Contame qué estás preparando.</h2><a href={WA}>Escribime por WhatsApp <ArrowRight/></a></section></main><Footer onLogin={onBook}/></div>}

const studentNav:ReadonlyArray<readonly[string,any]>=[['Inicio',LayoutDashboard],['Materiales',BookOpen],['Calendario',CalendarDays],['Reservar clase',Clock],['Mis reservas',FileText],['Pagos',CreditCard],['Cursos',PlayCircle],['Avisos',Bell],['Mi testimonio',Star]];
const adminNav:ReadonlyArray<readonly[string,any]>=[['Dashboard',LayoutDashboard],['Alumnos',Users],['Materiales',FileText],['Calendario',CalendarDays],['Reservas',Clock],['Pagos',CircleDollarSign],['Testimonios',Star],['Avisos',MessageSquareText]];
function Portal({role,onExit}:{role:'student'|'admin',onExit:()=>void}){const items=role==='student'?studentNav:adminNav;const[active,setActive]=useState(items[0][0]);return <div className={`portal ${role}`}><aside><div className="portal-brand"><img src={`${ASSET}logo-ciencias-exactas.jpg`} alt="Ciencias Exactas"/><small>{role==='student'?'Portal del alumno':'Panel administrativo'}</small></div><nav>{items.map(([label,Icon])=><button className={active===label?'active':''} onClick={()=>setActive(label)} key={label}><Icon/>{label}{(label==='Avisos'||label==='Pagos')&&<i>2</i>}</button>)}</nav><div className="aside-user"><div>{role==='student'?'VR':'MG'}</div><span><b>{role==='student'?'Valentina Romero':'Miriam Güeper'}</b><small>{role==='student'?'Alumno':'Administración'}</small></span><button onClick={onExit}><LogOut/></button></div></aside><div className="portal-body"><header><div><small>{role==='student'?'Portal del alumno':'Administración'} / {active}</small><h1>{active==='Inicio'||active==='Dashboard'?`¡Hola, ${role==='student'?'Valentina':'Miriam'}!`:active}</h1></div><div className="portal-tools"><button><Search/></button><button><Bell/><i>2</i></button><div>{role==='student'?'VR':'MG'}</div></div></header><main>{active===items[0][0]?<Dashboard role={role}/>:active==='Reservar clase'?<Booking/>:active==='Mi testimonio'?<TestimonialForm/>:<ModulePage title={active} role={role}/>}</main><nav className="bottom-nav">{items.slice(0,5).map(([label,Icon])=><button className={active===label?'active':''} onClick={()=>setActive(label)} key={label}><Icon/><small>{label}</small></button>)}</nav></div></div>}

function Dashboard({role}:{role:'student'|'admin'}){if(role==='admin')return <><div className="metrics admin-metrics">{[['Alumnos activos','148','+12%'],['Clases este mes','84','+8%'],['Pagos por validar','4','Revisar'],['Testimonios pendientes','3','Moderar']].map(m=><article key={m[0]}><span>{m[0]}</span><b>{m[1]}</b><small>{m[2]}</small></article>)}</div><div className="dashboard-grid"><section className="panel"><div className="panel-title"><h2>Clases de hoy</h2><button>Ver calendario</button></div><Schedule/></section><section className="panel"><div className="panel-title"><h2>Acciones rápidas</h2></div><div className="quick"><button><UserRound/>Nuevo alumno</button><button><Upload/>Subir material</button><button><CalendarDays/>Nuevo turno</button><button><MessageSquareText/>Crear aviso</button></div></section></div><section className="panel table-panel"><div className="panel-title"><h2>Pagos pendientes de validación</h2><button>Ver todos</button></div><table><tbody>{[['Lucía Benítez','Transferencia','Hace 8 min'],['Tomás Paz','MODO QR','Hace 21 min'],['Abril Soto','Transferencia','Hace 34 min']].map(r=><tr key={r[0]}><td><b>{r[0]}</b></td><td>{r[1]}</td><td>{r[2]}</td><td><button className="approve">Aprobar</button></td></tr>)}</tbody></table></section></>;
return <><section className="renewal"><Bell/><div><b>Tu abono vence en 7 días</b><span>Conservá tu día y horario renovando el acompañamiento CBC.</span></div><button>Renovar abono</button></section><section className="welcome"><div><span>Tu próxima clase</span><h2>Matemática 51 · Funciones</h2><p><CalendarDays/> Miércoles 8 de agosto · 17:30</p><p><Clock/> Duración: 2 horas · Modalidad online</p><button>Ver enlace de Meet <ArrowRight/></button></div><div className="date-card"><small>AGOSTO</small><b>08</b><span>Miércoles</span></div></section><div className="metrics">{[['Clases del mes','3 de 4'],['Estado del pago','Al día'],['Materiales nuevos','2'],['Cupo del grupo','4 de 5']].map(m=><article key={m[0]}><span>{m[0]}</span><b>{m[1]}</b></article>)}</div><div className="dashboard-grid"><section className="panel"><div className="panel-title"><h2>Próximas clases</h2><button>Ver calendario</button></div><Schedule/></section><section className="panel"><div className="panel-title"><h2>Accesos rápidos</h2></div><div className="quick"><button><CalendarDays/>Reservar clase</button><button><BookOpen/>Ver materiales</button><button><CreditCard/>Mis pagos</button><button><MessageSquareText/>Enviar consulta</button></div></section></div></>}
function Schedule(){return <div className="schedule">{[['09 AGO','Matemática 51','Funciones','18:00'],['16 AGO','Matemática 51','Derivadas','18:00'],['23 AGO','Matemática 51','Integrales','18:00']].map(x=><div key={x[0]}><time>{x[0]}</time><span><b>{x[1]}</b><small>{x[2]}</small></span><strong>{x[3]}</strong></div>)}</div>}

function Booking(){const[step,setStep]=useState(1);const[selected,setSelected]=useState('');return <section className="booking panel"><div className="booking-steps"><span className={step>=1?'active':''}>1 Servicio</span><span className={step>=2?'active':''}>2 Horario</span><span className={step>=3?'active':''}>3 Pago</span></div>{step===1&&<><h2>¿Qué servicio necesitás?</h2><div className="booking-options">{services.map(s=><button className={selected===s.title?'selected':''} onClick={()=>setSelected(s.title)} key={s.title}><span>{s.icon}</span><div><b>{s.title}</b><small>{s.period}</small></div><strong>{s.price}</strong></button>)}</div><button className="primary booking-next" disabled={!selected} onClick={()=>setStep(2)}>Continuar</button></>}{step===2&&<><h2>Elegí un horario disponible</h2><p>El cupo se guarda durante 2 horas mientras enviás el comprobante.</p><div className="slots">{['Lun 18:00','Mar 10:00','Mié 16:00','Jue 18:00','Vie 11:00'].map((x,i)=><button className={i===2?'full':''} disabled={i===2} key={x}>{x}<small>{i===2?'Cupo completo':selected==='Clases individuales'?'60 min':'2 h'}</small></button>)}</div><button className="primary booking-next" onClick={()=>setStep(3)}>Continuar al pago</button></>}{step===3&&<Payment selected={selected}/>}</section>}
function Payment({selected}:{selected:string}){const[method,setMethod]=useState<'modo'|'transfer'>('modo');return <><h2>Realizar el pago</h2><div className="policy"><b>Política de cancelación</b><span>Cancelación hasta 48 horas antes y reprogramación hasta 24 horas antes. Fuera de término se pierde el importe.</span></div><div className="payment-tabs"><button className={method==='modo'?'active':''} onClick={()=>setMethod('modo')}>QR de MODO</button><button className={method==='transfer'?'active':''} onClick={()=>setMethod('transfer')}>Transferencia</button></div>{method==='modo'?<div className="payment-box"><div className="qr">MODO<br/><small>QR</small></div><h3>Escaneá el código con MODO</h3><p>Al finalizar, enviá el comprobante por WhatsApp o correo.</p></div>:<div className="payment-box bank"><p><span>Alias</span><b>profeexactas</b><Copy/></p><p><span>CBU</span><b>0070325130004036330808</b><Copy/></p><p><span>Banco</span><b>Galicia</b></p><p><span>Titular</span><b>Miriam Gueper</b></p></div>}<div className="pending-note"><Clock/>La reserva de {selected} quedará pendiente de validación manual.</div><div className="receipt-actions"><a href={WA}>Enviar por WhatsApp</a><a href="mailto:profeexactasmg@gmail.com">Enviar por correo</a></div></>}
function TestimonialForm(){const[text,setText]=useState('');const[rating,setRating]=useState(5);return <section className="panel testimonial-form"><h2>Mi testimonio</h2><p>Tu comentario se publicará con tu nombre y foto de perfil después de ser aprobado.</p><div className="rating">{[1,2,3,4,5].map(n=><button onClick={()=>setRating(n)} className={n<=rating?'active':''} key={n}>*</button>)}</div><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Contanos tu experiencia..."/><button className="primary">{text?'Guardar cambios':'Enviar para aprobación'}</button><small>Podrás editarlo cuando quieras. La eliminación la gestiona la administración.</small></section>}
function ModulePage({title,role}:{title:string,role:string}){return <><div className="module-head"><button className="primary">+ {role==='admin'?'Crear nuevo':'Nueva consulta'}</button></div><section className="panel module"><div className="module-toolbar"><label><Search/><input placeholder={`Buscar en ${title.toLowerCase()}...`}/></label><button>Todos</button><button>Más recientes</button></div><div className="empty-icon">{title==='Materiales'?<BookOpen/>:<FileText/>}</div><h2>{title}</h2><p>Este módulo está listo para conectarse con los datos reales.</p><div className="module-cards">{[1,2,3].map(n=><article key={n}><span>{title.slice(0,1)}{n}</span><div><b>{title} · Elemento {n}</b><small>{title==='Pagos'?'Pendiente de validación':'Actualizado recientemente'}</small></div><button>{role==='admin'&&title==='Testimonios'?'Aprobar':'Ver detalle'}</button></article>)}</div></section></>}
function Footer({onLogin}:{onLogin:()=>void}){return <footer><div><div className="footer-brand"><img src={`${ASSET}logo-ciencias-exactas.jpg`} alt="Ciencias Exactas"/><span><strong>Miriam Güeper</strong><p>Profesora particular de Ciencias Exactas. Clases claras, cercanas y enfocadas en entender.</p></span></div><div><h4>Propuestas</h4><a href="#servicios">Clases individuales</a><a href="#servicios">Cursos intensivos</a><a href="#servicios">Ingreso universitario</a></div><div><h4>Plataforma</h4><button onClick={onLogin}>Acceso de alumnos</button><a href="#materias">Materias</a><a href="#faq">Preguntas frecuentes</a></div><div><h4>Contacto</h4><a href={WA}>+54 9 11 6103-9031</a><a href="mailto:profeexactasmg@gmail.com">profeexactasmg@gmail.com</a><a>J. E. Uriburu 1438 PB<br/>Recoleta, CABA</a></div></div><small>© 2026 Ciencias Exactas · Miriam Güeper.</small></footer>}
